prmr/JetUML

- src/ca/mcgill/cs/stg/jetuml/commands/DeleteNodeCommand.java
- test/cs/mcgill/cs/stg/jetuml/commands/TestDeleteNodeCommand.java
Tests for `RemoveNodeCommand`. Also, small fix: There is code duplication between `removeNode()`, `insertNode()` and `layout()`. aNeedsLayout is set to be true twice.
> Test remove node command

- src/ca/mcgill/cs/stg/jetuml/diagrams/SequenceDiagramGraph.java
- src/ca/mcgill/cs/stg/jetuml/graph/Graph.java
SequenceDiagramGraph reimplements the Graph class' deepFindNode method (which is used to implement selection) so that it gives priority to self-call call nodes when possible
> #144 Simple fix for self-calls selection issue

- src/ca/mcgill/cs/stg/jetuml/diagrams/SequenceDiagramGraph.java
- test/ca/mcgill/cs/stg/jetuml/diagrams/TestSequenceDiagramGraph.java
The earlier patch worked if the self-call was the only callee. This additionally fixes a more subtle case when a callNode has multiple callees, one of which is a self-call.
As illustrated here: http://i.imgur.com/5D0XZkt.png
> #144 Fix for case with multiple callees

- src/ca/mcgill/cs/stg/jetuml/diagrams/SequenceDiagramGraph.java
CallEdges may go from CallNodes to ImplicitParameterNodes, not just CallNodes, so use Node which covers both. Otherwise the selection tool crashes trying to cast a ImplicitParameterNode to CallNode when working with diagrams with a create edge.
#144 is still fixed either way, this is a distinct regression. Sorry for the mistake in the fix, everything is thoroughly tested now and this will be the last pull regarding this
> Use Node instead of CallNode in getCallees

- test/ca/mcgill/cs/jetuml/graph/TestUsageScenariosClassDiagram.java
Check only one edge of each type can exist at one time, and an attempt to
replace the edge will not succeed.
> Added tests for ClassDiagram

- src/ca/mcgill/cs/jetuml/views/edges/StateTransitionEdgeView.java
The first thing changed is to use atan2 instead of atan which avoids division by zero problems as exposed by the unit test.
The second thing changed is to fix a minor mistake in the getPosition() method of StateTransitionEdgeView.java which was preventing multiple state transition edges between two nodes from rendering correctly in the editor GUI. Without that fix if you have multiple state transition edges they will render as the same one in the GUI
Hopefully this helps
> #224 Fix some minor bugs relating to state diagram edges

- docs/install.md
Tested installation with different Oracle JDK version (Java 11/12/13) on macOS. All worked. Therefore, added a macOS instruction to help macOS users.
Also arranged the instruction a bit to improved clarity.
Also added the instruction to wiki for easier access.
Also fixed typo.
> Updated Installation Instruction

- src/ca/mcgill/cs/jetuml/diagram/Diagram.java
- src/ca/mcgill/cs/jetuml/diagram/nodes/ParentNode.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- test/ca/mcgill/cs/jetuml/diagram/TestDiagram.java
**Summary of Changes:**
Add a _rootNodesContain(Node): boolean_ method in the Diagram class so that one could easily check if a node is a root node of the Diagram. Add the reordering algorithm/method in the DiagramCanvasController class by iterating through the selected elements and reorder each element recursively.
**Achieved Performance:**
1. Whichever root node selected would be on top of all other root nodes of the Diagram.
2. Nested node: a. The selected child node would be on top of all the other children of the same parent node. b. The parent of the selected child node would be on top of all the other nodes within the same depth level as it is. If the parent is also a child node, do this recursively (until reaching the root nodes of the Diagram/ the node itself does not have a …
> #142 Reorder the selected elements to be drawn on top

- src/ca/mcgill/cs/jetuml/geom/Rectangle.java
- src/ca/mcgill/cs/jetuml/gui/SelectionModel.java
- Add a private helper method to recursively modify the bounds of the selected nodes in the `SelectionModel` class.
**Achieved Performance**
- Moving parent node through child node would not go beyond the canvas.
> #327 Modify the node bounds when moving parent node through child node

- src/ca/mcgill/cs/jetuml/diagram/ControlFlow.java
- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
- src/ca/mcgill/cs/jetuml/diagram/builder/SequenceDiagramBuilder.java
- src/ca/mcgill/cs/jetuml/diagram/edges/CallEdge.java
- src/ca/mcgill/cs/jetuml/diagram/edges/ConstructorEdge.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- src/ca/mcgill/cs/jetuml/viewers/edges/CallEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/EdgeViewerRegistry.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/CallNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/ImplicitParameterNodeViewer.java
- test/ca/mcgill/cs/jetuml/diagram/TestControlFlow.java
- test/ca/mcgill/cs/jetuml/diagram/builder/TestSequenceDiagramBuilder.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestCallNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestImplicitParameterNodeViewer.java
- Create a new type of edge `ConstructorEdge` which is inherited from the CallEdge.
- Use the `CallEdgeViewer` for drawing the `ConstructorEdge`.
- Modify the edge constraints to allow constructor call.
**Achieved Performance**
- A new type of edge to better distinguish the constructor call.
- Can create constructor call when the call edge lands on the `ImplicitParameterNode`.
**Concerns**
- The label of the `ConstructorEdge` is set to  "create" with bracket symbols by default. However, since we are inheriting directly from the CallEdge, which is a subclass of `SingleLabelEdge`, we can still change the label after creation.
> #269 Create Constructor Call Support in Sequence Diagram

- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- src/ca/mcgill/cs/jetuml/gui/SelectionModel.java
- test/ca/mcgill/cs/jetuml/gui/TestSelectionModel.java
**Summary of Changes** 
- Separate the methods to get the bounds of the entire selection including the bounds of the parent nodes or excluding them.
**Achieved Behavior** 
- Shift the elements when the pasted elements overlap with the original elements.
> #338 Copy-Paste Issue

- src/ca/mcgill/cs/jetuml/diagram/builder/ClassDiagramBuilder.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/PackageNodeViewer.java
- test/ca/mcgill/cs/jetuml/diagram/builder/TestClassDiagramBuilder.java
- Modify the position of the `PackageNode` returned by the method. 
- Change the positioning of the first child node created within the  `PackageNode` to be wrapped tightly.
**Achieved Behaviour**
- When drawing the 1st node, the `PackageNode` would always wraps its child tightly.
- When drawing multiple nodes, we can still adjust the package node’s size by moving the child nodes around, but we could not move the `PackageNode` by its children.
> #340 Modify the Drawing of Package Nodes

- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
- After the child node is deleted, change the original position of the `PackageNode` to stay in the same position relative to its child node.
> #340 Reposition the package node

- src/ca/mcgill/cs/jetuml/diagram/Diagram.java
- test/ca/mcgill/cs/jetuml/diagram/TestDiagram.java
Avoid reordering call nodes when the nodes are selected in the sequence diagram.
> Sequence diagram fix

- src/ca/mcgill/cs/jetuml/diagram/ControlFlow.java
- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
- src/ca/mcgill/cs/jetuml/diagram/builder/SequenceDiagramBuilder.java
- test/ca/mcgill/cs/jetuml/diagram/TestControlFlow.java
- test/ca/mcgill/cs/jetuml/diagram/TestUsageScenariosSequenceDiagram.java
- test/ca/mcgill/cs/jetuml/persistence/TestPersistenceService.java
- Added methods to obtain the upstream `DiagramElement`s.
- Added the method to obtain the corresponding `ReturnEdge`s.
- Modified and added new tests.
- Updated the code documentation.
**Sample Diagram**
Below is the sample diagram created in the `TestControlFlow` class.
> #353 Modify the control-flow of element deletion in Sequence Diagram

- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
- src/ca/mcgill/cs/jetuml/diagram/builder/SequenceDiagramBuilder.java
- Modified the `tweakOrder` method to ensure that the `CallNode`s in the Sequence Diagram can be reinserted properly in the undo operation.
- Modified the control-flow in the `getCoRemovals` method.
> #353 Modify the element deletion order in the undo method

- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
Modify the comparison logic in the `tweakOrder` method, for nodes that have parents:
1. If two nodes have the same parent, place the latter child node at the front.
2. If two nodes have different parents, order the nodes according to the positions of their parent nodes in `rootNodes` of the diagram.
> #353 Modify the tweakOrder method

- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- Modify the method in the `DiagramCanvasController` class to handle the auto-selection.
**Achieved Performance**
- If the user clicks on the canvas and the click is within an object's bound, then automatically activate the Selection Tool in the toolbar and select the element clicked.
- Auto-selection is implemented only for nodes other than `ImplicitParameterNode`s and `FieldNode`s since we may actually want to add a child node or a field to the node under the click.
**Concerns**
- Auto-selection is disabled for edges since we may want to detect the end node of the edge instead of selecting the node.
> #363 Add auto-selection algorithm to avoid redundant node creation

- src/ca/mcgill/cs/jetuml/diagram/ControlFlow.java
- src/ca/mcgill/cs/jetuml/diagram/builder/DiagramBuilder.java
- src/ca/mcgill/cs/jetuml/diagram/builder/SequenceDiagramBuilder.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- test/ca/mcgill/cs/jetuml/diagram/TestControlFlow.java
- test/ca/mcgill/cs/jetuml/diagram/builder/TestSequenceDiagramBuilder.java
- Moved the `canCreateConstructorCall` method to the `SequenceDiagramBuilder` class.
- Modified the `canCreateConstructorCall` method to constrain the start node of the constructor call to be either an `ImplicitParameterNode` with no child nodes or a `CallNode`.
- Added a helper method in the class `ControlFlow`.
- Added tests for corresponding methods.
**Concerns**
- The class `DiagramBuilder` cannot be tested directly since it is an abstract class.
> #369 Modify constraints in the Sequence Diagram for constructor call creation

- src/ca/mcgill/cs/jetuml/JetUML.java
- src/ca/mcgill/cs/jetuml/gui/EditorFrame.java
This change opens files that are passed in to the application through the arguments, which allows you to "Open With" a .jet file. I tested the integration with Debian/Gnome/Nautilus.
> #382 Open files passed in as arguments

- src/ca/mcgill/cs/jetuml/JetUML.properties
- src/ca/mcgill/cs/jetuml/gui/DiagramTab.java
- src/ca/mcgill/cs/jetuml/gui/EditorFrame.java
- Zooming in/out uses an exponential scale, with a base of 1.25
- Each tab maintains its own independent zoom level
- Allows user to reset zoom using `ctrl + 0`.
- This required adding a filter on the toolbar selection hotkeys
Although #328 mentions using `ctrl + '+'` to zoom in, I bound it to `ctrl + '='` as I believe this shortcut is much more intuitive. The perfect solution would bind both `ctrl + '+'` and `ctrl + '='` to this function though unfortunately that is not easily achieved using `MenuItem`s.
Icons for the new menu items are missing.
> [#328] Support zooming the diagram

- test/ca/mcgill/cs/jetuml/persistence/TestPersistenceService.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestFieldNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestObjectNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestPackageNodeViewer.java
Summary of the Changes:
   After the geometryUtil class updates (#399), there were some tests that were not passing on MacOS, mainly the OS-dependent bounds for certain notes; use case dependency edge; implicit parameter nodes, self call edges, and call nodes in sequence diagrams etc. To fix, I went through the tester, and if the change in bound was like 1 pixel, I just changed it. If it was more, I checked the diagram to make sure it rendered properly and if so, I changed it.
   Most of the bound changes actually matched that for Windows, and if not, become significantly closer. The worst case discrepancy went from +- 20 pixels to +- 5 pixels.
> #400 Verify and update failing tests

- src/ca/mcgill/cs/jetuml/views/StringViewer.java
Summary of changes:
The `StringViewer.draw` method changed the state of the graphics content, which affected other components. These changes (the text alignment) are now restored upon leaving the method.
> #402 Save and restore the text alignment when drawing strings

- src/ca/mcgill/cs/jetuml/viewers/edges/SegmentedEdgeViewer.java
Summary of Changes:
Before, the text was indiscriminately set to center horizontally. However, this didn't take into account if the ending node was above or below the starting endpoint, which, due to how the string's vertical position is calculated, made it not properly centered. This change checks this and sets the baseline appropriately.
> #409 Set text baseline conditioned on if the endpoint is above the start

- src/ca/mcgill/cs/jetuml/viewers/edges/AbstractEdgeViewer.java
- src/ca/mcgill/cs/jetuml/views/FontMetrics.java
- src/ca/mcgill/cs/jetuml/views/StringViewer.java
- test/ca/mcgill/cs/jetuml/persistence/TestPersistenceService.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestFieldNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestObjectNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestPackageNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestTypeNodeViewer.java
- test/ca/mcgill/cs/jetuml/views/TestFontMetrics.java
Summary of the changes:
- Made a class that represents the font metrics for a particular font. It can take in a string, and then output the dimensions of the string, taking into account any potential leading or ascent that may arise. This dimension is tight with respect to these values.
- Changed classes (`StringViewer` and `AbstractEdgeViewer`) that rely on text dimensions directly to utilize this class, rather than doing the calculations themselves.
- Fix tests that were made broken by the change in how precisely the dimensions are determined (notably, it takes into account any _potential_ ascent or descent, as opposed to the old version which only accounted for it if it was there, and making the bounds tighter
- Added a test for the new class that tests both that the dimension …
> 413 refactor the string viewer

- test/ca/mcgill/cs/jetuml/diagram/TestUsageScenariosObjectDiagram.java
- test/ca/mcgill/cs/jetuml/persistence/TestPersistenceService.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestFieldNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestObjectNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestPackageNodeViewer.java
- test/ca/mcgill/cs/jetuml/views/TestFontMetrics.java
Summary of Changes:
There were some test cases that were failing due to a comment I addressed, but failed to recheck and update the tests. This PR includes the fixes for these tests.
Some of these tests are OS dependent, so it's only a guarantee that the tests no longer fail on MacOS
> #413 Fix tests that failed due to switch from cast to round (on Mac)

- test/ca/mcgill/cs/jetuml/persistence/TestPersistenceService.java
There were tests that were failing on Mac, but not Windows. These tests should now be fixed.
Note: I had to add an `osDependent` call to one of the `assertEquals`. I don't know what the value for people running Linux is, so I just copies values from similar tests.
> #416 Fix failing tests for Mac

- src/ca/mcgill/cs/jetuml/viewers/nodes/ActorNodeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/nodes/TestActorNodeViewer.java
Summary of Changes:
* Changed the text positioning so that it calculates it based on the default width of the node and the width of the text, rather than the current bounds of the width
* Changed the bounds to account for this change
* Fix the one failing test
> 419 actor node labels not centered

- src/ca/mcgill/cs/jetuml/viewers/edges/AbstractEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/CallEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/LabeledStraightEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/SegmentedEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/StateTransitionEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/UseCaseDependencyEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/AbstractPackageNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/ActorNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/FieldNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/ImplicitParameterNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/NoteNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/ObjectNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/PackageDescriptionNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/StateNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/TypeNodeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/nodes/UseCaseNodeViewer.java
- src/ca/mcgill/cs/jetuml/views/StringViewer.java
- test/ca/mcgill/cs/jetuml/views/TestStringViewer.java
Summary of Changes:
`StringViewer` is now flyweight. Furthermore, previous enums are replaced with 3: `VerticalAlign`, `HorizontalAlign`, and `TextDecorations` (which includes bolded, underlined, and padded text, the last of which is new). To instantiate a `StringViewer`, one must pass a vertical alignment, a horizontal alignment, and an `EnumSet` containing objects of type `TextDecorations` which specify which decorations to apply. The set of these properties form the key of the `Map` representing the cache of already-created `StringViewers`
Furthermore, classes that dealt with text in some form, but not via `StringViewer`, now rely on `StringViewer` (`AbstractEdgeViewer`, `StateTransitionEdgeViewer`, and `SegmentedEdgeViewer`). These classes were what prompted the addition of the …
> #422 refactor code involving text

- src/ca/mcgill/cs/jetuml/viewers/edges/AbstractEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/LabeledStraightEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/SegmentedEdgeViewer.java
- src/ca/mcgill/cs/jetuml/viewers/edges/StateTransitionEdgeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestAssociationEdgeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestDependencyEdgeViewer.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestStateTransitionEdgeViewer.java
The line lengths of LabeledStraightEdges, SegmentedEdges, and StateTransitionEdges is now determined dynamically based on the horizontal and vertical distances between the two points that the segment relates. During this code addition, it was noticed that some code for StateTransitionEdge label wrapping was unreachable so it was removed. 
The labels of horizontal segments now hover above the arrowhead to match the behaviour of vertical segment labels. 
The labels of SegmentedEdges no longer overlaps with the segments themselves. Logic was added to the relevant method to be able to differentiate between a "step up" segment and a "step down" segment. Before the modifications of this pull request, the behaviour was different for two same nodes connected by an edge when the nodes were …
> #446 Improvements to Edge Label Alignment and Layout

- src/ca/mcgill/cs/jetuml/viewers/nodes/NodeViewerRegistry.java
Corrects some copy-and-paste typos in the Javadocs.
> Fix typos in comments in NodeViewerRegistry

- .classpath
- src/ca/mcgill/cs/jetuml/diagram/builder/SequenceDiagramBuilder.java
- test/ca/mcgill/cs/jetuml/diagram/TestControlFlow.java
- test/ca/mcgill/cs/jetuml/diagram/builder/TestSequenceDiagramBuilder.java
Changes were made to fix issue #437, ensuring that when the user deletes a `ConstructorEdge`, downstream `ImplicitParameterNode` objects are not deleted, as well. 
To fix this, a conditional statement was added to `SequenceDiagramBuilder.getCoRemovals()` which checks if the input diagram element is a `ConstructorEdge`. If so, downstream `ImplicitParameterNode` objects are removed from the list to be returned. A new test was written to consider the behavior of `getCoRemovals()` with a `ConstructorEdge`. An unrelated annotation error was also fixed in `TestControlFlow`. 
**Here is an example scenario:**
Before applying this fix:
After fixing applying this fix:
> Issue#437 Fix get co-removals for sequence diagrams

- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
This addresses the issues brought in in #445 . However, we could now open a separate bug ticket for the following: on a "MouseDragged" event, we handle the movement of the selection in DiagramCanvasController::moveSelection. In the case where the entire selection bounds is close the wall of the canvas, we obtain an upper bound on the tracking speed due to the logic in DiagramCanvasController::moveSelection. This could be fixed by only checking whether we exceed the "relevant" canvas bounds: the canvas bounds that the "entire selection bounds" are approaching.
> Bug fix 445

- src/ca/mcgill/cs/jetuml/diagram/DiagramType.java
- src/ca/mcgill/cs/jetuml/geom/EdgePath.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvas.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- src/ca/mcgill/cs/jetuml/viewers/ClassDiagramViewer.java
- src/ca/mcgill/cs/jetuml/viewers/DiagramViewer.java
- src/ca/mcgill/cs/jetuml/viewers/EdgePriority.java
- src/ca/mcgill/cs/jetuml/viewers/ImageCreator.java
- src/ca/mcgill/cs/jetuml/viewers/Layouter.java
- src/ca/mcgill/cs/jetuml/viewers/NodeCorner.java
- src/ca/mcgill/cs/jetuml/viewers/edges/EdgeStorage.java
- src/ca/mcgill/cs/jetuml/viewers/edges/NodeIndex.java
- src/ca/mcgill/cs/jetuml/viewers/edges/StoredEdgeViewer.java
- test/ca/mcgill/cs/jetuml/geom/TestEdgePath.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestEdgeStorage.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestNodeIndex.java
- test/ca/mcgill/cs/jetuml/viewers/edges/TestStoredEdgeViewer.java
- test/ca/mcgill/cs/jetuml/views/TestClassDiagramViewer.java
- test/ca/mcgill/cs/jetuml/views/TestEdgePriority.java
- test/ca/mcgill/cs/jetuml/views/TestLayouter.java
- test/ca/mcgill/cs/jetuml/views/TestNodeCorner.java
**In order to plan the paths of edges in class diagrams, several initial changes are needed:**
1. A way to represent the path of an edge
2. A way to store the paths of edges
3. A way to classify edges so that their paths can be planned in a predictable order
To meet these requirements 3 classes: `EdgePath`, `EdgeStorage`, and `EdgePriority` were added.
An `EdgePath` class was added, which represents the path of an edge in a class diagram as a list of `Point`s. An `EdgeStorage` class was created, which maps the edges of a class diagram to `EdgePath`s. 
Once the `Layouter` class is implemented, it will plan the `EdgePath`s of edges in a class diagram and store them in `EdgeStorage`. Then, these stored paths can be used to draw clean, readable class diagrams without edge overlapping. 
The …
> #375 Add EdgePath, EdgeStorage, and EdgePriority

- src/ca/mcgill/cs/jetuml/gui/DiagramCanvas.java
- src/ca/mcgill/cs/jetuml/gui/DiagramCanvasController.java
- test/ca/mcgill/cs/jetuml/geom/TestEdgePath.java
Fix the draw selection handles control flow for class diagrams so that the selection handles for stored edges are drawn using their stored connection points. 
Remove unused/duplicate imports
> Issue375 Fix selection handle drawing for class diagrams

- docs/install.md
If your package manager has JetUML in its repos, getting the software that way may be preferable to manually downloading and updating it.
I've been maintaining a [build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jetuml) for the thin jar on the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) for two years.[^1]
It seems there was also work on getting JetUML onto flathub #433, so imo it'd be useful to list these places in the docs.
[^1]: Basically this means that users of Arch based Distros can get JetUML like any other package. On installation, a script downloads the latest jar from your GitHub releases and creates desktop shortcuts and scripts that will call Java with the correct parameters to launch the app.
> Add note about OS package managers

- src/org/jetuml/diagram/builder/DiagramBuilder.java
- src/org/jetuml/diagram/builder/SequenceDiagramBuilder.java
Issue #484 Node Renderer Instance from DiagramRenderer instance
* In SequenceDiagramRenderer use the existing instance to create an ImplicitParameterNode instance
* In DiagramBuilder use the existing instance to create a PackageNodeRenderer instance
> Fix issue #484

- .classpath
- src/org/jetuml/rendering/FontMetrics.java
- src/org/jetuml/rendering/StringRenderer.java
- src/org/jetuml/rendering/nodes/TypeNodeRenderer.java
Users can now underline their static features by surrounding them with the underscore ("_") markup.
E.g. \_getHeight(): int\_
Leading and trailing spaces result in no underlining.
Detection of markups is done in the `TypeNodeRenderer` class and drawing the underline by `StringRenderer`.
Adjustments were made in the `draw` method of `StringRenderer` class to accommodate underlining of text aligned to the top.
> [#512] Underlining Feature for Static Attributes and Methods in Class Diagrams

- src/org/jetuml/gui/NotificationService.java
- src/org/jetuml/gui/ToastNotification.java
This PR is a simple fix for the flashing bug mentioned in #524.
The use of `Stage::close` with JavaFX when the window is minimized makes it flash on the taskbar.
Therefore, notifications are not closed anymore once they reach the end of their lifespan.
They are moved to another list, `aDeadNotifications`, and all the notifications in this list are closed and removed when a new notification is spawned. I assumed that notifications are only spawned when the window is maximized (since they are all based on user actions).
> [#524] Taskbar Flashing Bug Fix

- src/org/jetuml/rendering/StringRenderer.java
- src/org/jetuml/rendering/nodes/TypeNodeRenderer.java
In addition to the underlining feature, users can now denote abstract class names and methods by surrounding them with a forward slash ("/").
E.g.   /abstractClassName/
> [#512] Italics Feature

- src/org/jetuml/rendering/CanvasFont.java
- src/org/jetuml/rendering/StringRenderer.java
- src/org/jetuml/rendering/nodes/TypeNodeRenderer.java
- test/org/jetuml/rendering/TestFontMetrics.java
- test/org/jetuml/rendering/TestStringViewer.java
Class `StringRenderer` provides an interface for subsystems to render strings to their particular needs for different font styles and text alignments. 
The redesign cleaned up class `StringRenderer` to provide a minimal interface to work with. This involved moving the static inner class `CanvasFont` of `StringRenderer` to a class of its own.
> StringRenderer Redesign

- src/org/jetuml/rendering/StringRenderer.java
- src/org/jetuml/rendering/nodes/TypeNodeRenderer.java
- test/org/jetuml/layouttests/AbstractTestDiagramLayout.java
- Fix unit tests to set default and restore user defined font.
- Allow italicizing abstract class names with stereotypes.
> [#512] Italicizing the Names of Abstract Classes with Stereotypes

- src/org/jetuml/gui/PropertySheet.java
Scroll bars unnecessarily appear on the `TextArea` in the properties dialog of a node, if the user has their monitor display setting at a higher scale (greater than 100% on Windows).
The scroll bars appear because the dimension of the `TextArea` is larger than the space that is allocated by its `ScrollPane` parent. This mismatch seems to occur due to JavaFX not considering the effect scale has on dimension computation for different components.
> [#553] Scroll Bar Fix

- README.md
- index.md
This change creates a separate landing page for the website and the GitHub repo.
> [#559] Create Separate Landing Page for Website and GitHub Repository
